"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-19 19:53:48.047827
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name', name='uq_team_org_name')
    )
    op.create_index(op.f('ix_team_org_id'), 'team', ['org_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('admin', 'lead', 'developer', name='user_role'), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('auth_provider', sa.String(length=50), server_default='local', nullable=False),
    sa.Column('external_subject', sa.String(length=320), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'email', name='uq_user_org_email')
    )
    op.create_index(op.f('ix_user_org_id'), 'user', ['org_id'], unique=False)
    op.create_table('api_token',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_api_token_org_id'), 'api_token', ['org_id'], unique=False)
    op.create_index(op.f('ix_api_token_user_id'), 'api_token', ['user_id'], unique=False)
    op.create_table('login_session',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_login_session_user_id'), 'login_session', ['user_id'], unique=False)
    op.create_table('team_member',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'user_id')
    )
    op.create_index(op.f('ix_team_member_user_id'), 'team_member', ['user_id'], unique=False)
    op.create_table('workflow_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('task_ref', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('triggered_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_run_org_id'), 'workflow_run', ['org_id'], unique=False)
    op.create_table('session',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('human_owner_id', sa.UUID(), nullable=False),
    sa.Column('origin', sa.Enum('human', 'workflow', name='session_origin'), nullable=False),
    sa.Column('workflow_run_id', sa.UUID(), nullable=True),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('agent_vendor', sa.String(length=64), nullable=False),
    sa.Column('agent_version', sa.String(length=64), nullable=True),
    sa.Column('agent_model', sa.String(length=120), nullable=True),
    sa.Column('models_used', sa.ARRAY(sa.String(length=120)), server_default='{}', nullable=False),
    sa.Column('repo', sa.String(length=300), nullable=True),
    sa.Column('branch', sa.String(length=200), nullable=True),
    sa.Column('task_ref', sa.String(length=300), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', sa.Enum('completed', 'abandoned', 'errored', 'unknown', name='session_outcome'), nullable=False),
    sa.Column('end_reason', sa.String(length=64), nullable=True),
    sa.Column('turn_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('collector_version', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['human_owner_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_run.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'agent_vendor', 'external_id', name='uq_session_external')
    )
    op.create_index('ix_session_open', 'session', ['org_id', 'last_seen_at'], unique=False, postgresql_where=sa.text('ended_at IS NULL'))
    op.create_index(op.f('ix_session_org_id'), 'session', ['org_id'], unique=False)
    op.create_index('ix_session_org_repo', 'session', ['org_id', 'repo'], unique=False)
    op.create_index('ix_session_org_started', 'session', ['org_id', 'started_at'], unique=False)
    op.create_index('ix_session_owner_started', 'session', ['human_owner_id', 'started_at'], unique=False)
    op.create_table('decision',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('origin', sa.Enum('review_comment', 'correction', 'revert', name='decision_origin'), nullable=False),
    sa.Column('affected_paths', sa.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('decided_by_id', sa.UUID(), nullable=True),
    sa.Column('source_session_id', sa.UUID(), nullable=True),
    sa.Column('superseded_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_session_id'], ['session.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['decision.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_org_id'), 'decision', ['org_id'], unique=False)
    op.create_table('fact',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('producing_command', sa.Text(), nullable=False),
    sa.Column('scope', sa.Enum('repo', 'service', 'org', name='fact_scope'), nullable=False),
    sa.Column('scope_ref', sa.String(length=300), nullable=True),
    sa.Column('source_session_id', sa.UUID(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('state', sa.Enum('fresh', 'drifted', 'dead', name='fact_state'), nullable=False),
    sa.Column('ttl_seconds', sa.Integer(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_session_id'], ['session.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fact_org_id'), 'fact', ['org_id'], unique=False)
    op.create_table('ingest_event',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_ingest_event_session_id'), 'ingest_event', ['session_id'], unique=False)
    op.create_table('retrieval',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('requester_user_id', sa.UUID(), nullable=True),
    sa.Column('agent_vendor', sa.String(length=64), nullable=True),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('facts_served', sa.ARRAY(sa.UUID()), server_default='{}', nullable=False),
    sa.Column('tokens_saved_estimate', sa.BigInteger(), nullable=True),
    sa.Column('was_used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retrieval_org_id'), 'retrieval', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retrieval_org_id'), table_name='retrieval')
    op.drop_table('retrieval')
    op.drop_index(op.f('ix_ingest_event_session_id'), table_name='ingest_event')
    op.drop_table('ingest_event')
    op.drop_index(op.f('ix_fact_org_id'), table_name='fact')
    op.drop_table('fact')
    op.drop_index(op.f('ix_decision_org_id'), table_name='decision')
    op.drop_table('decision')
    op.drop_index('ix_session_owner_started', table_name='session')
    op.drop_index('ix_session_org_started', table_name='session')
    op.drop_index('ix_session_org_repo', table_name='session')
    op.drop_index(op.f('ix_session_org_id'), table_name='session')
    op.drop_index('ix_session_open', table_name='session', postgresql_where=sa.text('ended_at IS NULL'))
    op.drop_table('session')
    op.drop_index(op.f('ix_workflow_run_org_id'), table_name='workflow_run')
    op.drop_table('workflow_run')
    op.drop_index(op.f('ix_team_member_user_id'), table_name='team_member')
    op.drop_table('team_member')
    op.drop_index(op.f('ix_login_session_user_id'), table_name='login_session')
    op.drop_table('login_session')
    op.drop_index(op.f('ix_api_token_user_id'), table_name='api_token')
    op.drop_index(op.f('ix_api_token_org_id'), table_name='api_token')
    op.drop_table('api_token')
    op.drop_index(op.f('ix_user_org_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_team_org_id'), table_name='team')
    op.drop_table('team')
    op.drop_table('organization')
    for enum in ('user_role', 'session_origin', 'session_outcome', 'fact_scope', 'fact_state', 'decision_origin'):
        op.execute(f'DROP TYPE IF EXISTS {enum}')
    # ### end Alembic commands ###
